CREATE TABLE collection (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE platform (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	manufacturer TEXT NOT NULL,
	name TEXT NOT NULL
);

CREATE TABLE game (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	developer TEXT NULL,
	publisher TEXT NULL,
	year INTEGER NULL,
	platform INTEGER NOT NULL,
	collection INTEGER NULL,
	
	FOREIGN KEY (platform) REFERENCES platform(id),
	FOREIGN KEY (collection) REFERENCES collection(id)
);

CREATE TABLE sessionType (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL
);

CREATE TABLE run (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	game INTEGER NOT NULL,
	name TEXT NOT NULL,

	FOREIGN KEY (game) REFERENCES game(id)
);

CREATE TABLE session (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	startedAt TEXT NOT NULL,
	stoppedAt TEXT NOT NULL,
	game INTEGER NOT NULL,
	sessionType INTEGER NULL,
	run INTEGER NULL,
	note TEXT NULL,
	
	FOREIGN KEY (game) REFERENCES game(id),
	FOREIGN KEY (sessionType) REFERENCES sessionType(id),
	FOREIGN KEY (run) REFERENCES run(id)
);